### ISSUE TITLE
CordCloud Action 运行异常

### ISSUE THREAD

**Issue by persia7emily** [yanglbme/cordcloud-action#2]
一直运行良好，没有改动。直至5天前开始失败。

错误信息包括：

- Expecting value: line 1 column 1 (char 0)
- HTTPSConnectionPool(host='c-cloud.xyz', port=443): Max retries exceeded with url: /auth/login (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f17dd7fb580>: Failed to establish a new connection: [Errno -2] Name or service not known'))
- HTTPSConnectionPool(host='cordcloud.us', port=443): Max retries exceeded with url: /auth/login (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1123)')))

![2022-12-28_192121](https://user-images.githubusercontent.com/46820597/209804632-da2b98a9-fa2e-4b31-a8f6-12bc8c11587a.png)

![2022-12-28_192159](https://user-images.githubusercontent.com/46820597/209804652-bcc2d6b0-aa96-4f06-8ada-74f92667cd14.png)

**Comment by yanglbme** [comment]
确实失败了，cordcloud 可能有改动，我看看是啥原因

**Comment by yanglbme** [comment]
@persia7emily 已修复，谢谢反馈
