### ISSUE TITLE
执行找不到email配置

### ISSUE THREAD

**Issue by hUmBlesOng** [yanglbme/cordcloud-action#5]
执行的时候会报错找不到 email
<img width="1556" alt="image" src="https://github.com/yanglbme/cordcloud-action/assets/31310908/f50fd048-b782-4d97-b966-c761f1104f37">

相关的secret已经配置了
<img width="1425" alt="image" src="https://github.com/yanglbme/cordcloud-action/assets/31310908/500a4ffa-6872-49cf-a6e6-54c88d48a47d">

这是我的yml文件
<img width="875" alt="image" src="https://github.com/yanglbme/cordcloud-action/assets/31310908/932161e1-d577-4297-b4df-92ff58ec0fa9">

**Comment by yanglbme** [comment]
![image](https://github.com/yanglbme/cordcloud-action/assets/21008209/28383c81-7ea7-42ea-b86c-7e0b61e2dcde)


设置在 Actions 中吧 @hUmBlesOng
